### ISSUE TITLE
pull fails on fs-layer

### ISSUE THREAD

**Issue by dehubbed** [oskapt/docker-openfire#1]
Your openfire on docker sounds like just what I need to run multiple servers (serving multiple domains) on one machine. However the docker pull command fails when it's trying to download the 300+ MB "fs-layer" from the registry. It aborts at the ~40MB mark every time. This is possibly not your fault.

**Comment by oskapt** [comment]
Interesting.  I'll look into it.  I haven't updated it for recent docker versions, so give me a few days to bring it up to speed.  

Adrian

**Comment by dehubbed** [comment]
After the pull failed I followed the build instructions to build it myself and it seems to work fine as far as I can tell in an hour or so usage. This is with latest binary and on Debian Wheezy even.

**Comment by oskapt** [comment]
It seems that I already updated the EXPOSE directives, et al, for 0.7, so I did a version bump to 3.9.1 and updated the README.  Glad to hear that things are working for you.  If you need to upgrade, it's as simple as re-doing the build steps.  I just bumped my installation to 3.9.1 with no issues.

Thanks for using my container.  It's nice that it benefits someone else besides me.  :)

Adrian
