### ISSUE TITLE
run.sh needs to expose port 9090

### ISSUE THREAD

**Issue by dehubbed** [oskapt/docker-openfire#2]
You're asking users to access localhost:9090 but run.sh exposes port 9091.

**Comment by oskapt** [comment]
This is super old, but it's fixed. It was a typo in the README, which has now been updated to clarify the difference between HTTP (9090) and HTTPS (9091).

Today's release runs Openfire 4.0.2 and is backed by Alpine Linux for a much smaller container size (624M down to 151M). Give it a spin!

**Comment by dehubbed** [comment]
Cool cool thanks. This thing is super helpful. Because openfire only allows 1 domain, i.e. users all have some ID like user@mydomain.com. To support multiple domains I have to run multiple openfire servers on one machine and thanks to your docker image I can do that.
